# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
script:
- xcodebuild test -workspace Example/VMaskTextField.xcworkspace -scheme VMaskTextField -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
